name: Metrics

on:
  schedule:
    - cron: "0 */12 * * *"  # Cada 12 horas
  workflow_dispatch:

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v3

      # Generar métricas clásicas
      - name: Generate GitHub metrics
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: YovannyRn
          template: classic
          base: header, activity, community, repositories, metadata
          plugin_languages: yes
          plugin_languages_ignored: html, css
          plugin_languages_limit: 10
          plugin_languages_sections: most-used
          plugin_topics: yes
          plugin_topics_mode: mastered
          plugin_topics_sort: stars
          plugin_lines: yes
          config_timezone: Europe/Madrid

      # Renombrar y guardar el SVG clásico
      - name: Commit classic metrics
        run: |
          mv metrics.svg github-metrics.svg
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add github-metrics.svg
          git commit -m "update classic metrics" || echo "No changes"
          git push

      # Generar calendario medio año
      - name: Generate Half-year calendar
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: YovannyRn
          filename: github-metrics.isocalendar.svg
          plugin_isocalendar: yes
          base: ""  # Solo el plugin

      - name: Commit Half-year calendar
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add github-metrics.isocalendar.svg
          git commit -m "update half-year calendar" || echo "No changes"
          git push

      # Generar calendario año completo
      - name: Generate Full-year calendar
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: YovannyRn
          filename: github-metrics.isocalendar.fullyear.svg
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year
          base: ""  # Solo el plugin

      - name: Commit Full-year calendar
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add github-metrics.isocalendar.fullyear.svg
          git commit -m "update full-year calendar" || echo "No changes"
          git push
