name: Metrics

on:
  schedule:
    - cron: "0 */12 * * *"
  workflow_dispatch:

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v3

      - name: Generate GitHub metrics
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: YovannyRn
          template: classic
          base: header, activity, community, repositories, metadata
          plugin_languages: yes
          plugin_languages_ignored: html, css
          plugin_languages_limit: 10
          plugin_languages_sections: most-used
          plugin_topics: yes
          plugin_topics_mode: mastered
          plugin_topics_sort: stars
          plugin_lines: yes
          config_timezone: Europe/Madrid

      - name: Commit the metrics
        run: |
          mv metrics.svg github-metrics.svg
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add github-metrics.svg
          git commit -m "update metrics" || echo "No changes"
          git push
